version: '3.8'
services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
    restart: unless-stopped
  upstream:
    image: python:3.9-slim
    container_name: upstream
    # including a /internal/_index.html file which the content is 'Hello'
    working_dir: /home
    command: python -m http.server 8000
    volumes:
      - ./upstream_server:/home
    restart: unless-stopped
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: unless-stopped
